+incdir+$ROOT_PATH/rtl

-sverilog
$ROOT_PATH/rtl/AMDCHIPKILL_DECODER.sv
$ROOT_PATH/rtl/GFMULT.sv
$ROOT_PATH/rtl/GFEXP.sv
$ROOT_PATH/rtl/GFDIV.sv
$ROOT_PATH/rtl/ERROR_INFORMATION.sv
$ROOT_PATH/rtl/SYNDROME_GENERATOR.sv
$ROOT_PATH/rtl/ERROR_LOCATION.sv