+incdir+$ROOT_PATH/rtl

-sverilog
$ROOT_PATH/rtl/DECODER.sv
$ROOT_PATH/rtl/GFADD.sv
$ROOT_PATH/rtl/GFMULT.sv
$ROOT_PATH/rtl/GFEXP.sv
$ROOT_PATH/rtl/GFDIV.sv
$ROOT_PATH/rtl/GFINDEX.sv
$ROOT_PATH/rtl/ERROR_ERASURE_INFORMATION.sv
$ROOT_PATH/rtl/ERROR_INFORMATION.sv
$ROOT_PATH/rtl/ERASURE_INFORMATION.sv
$ROOT_PATH/rtl/SYNDROME_GENERATOR.sv
$ROOT_PATH/rtl/ERROR_LOCATION.sv
$ROOT_PATH/rtl/ERASURE_LOCATION.sv